server:
  error:
    include-message: always
    include-binding-errors: always
  shutdown: graceful
  forward-headers-strategy: framework
  tomcat:
    connection-timeout: 10s
    keep-alive-timeout: 20s
    threads:
      max: 50
      min-spare: 5

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  datasource:
    username: ${app.postgres.user}
    password: ${app.postgres.password}
    url: jdbc:postgresql://${app.postgres.host}:${app.postgres.port}/${app.postgres.database}

  flyway:
    enabled: true
    locations: classpath:db/migration

  keycloak:
    server-url: http://localhost:8080
    server-external-url: http://localhost:8080
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.keycloak.server-external-url}/realms/betting-realm
          jwk-set-uri: ${spring.keycloak.server-url}/realms/betting-realm/protocol/openid-connect/certs

  cloud:
    function:
      definition: startSaga;reserveCustomerBalanceStage;reserveProductStockStage
    stream:
      default:
        producer:
          partition-count: 1
          retry-count: 5
        consumer:
          concurrency: 1
      bindings:
        reserveCustomerBalanceStage-in-0:
          destination: CUSTOMER.events
          group: order-service-reserve-balance-group
        reserveProductStockStage-in-0:
          destination: PRODUCT.events
          group: order-service-reserve-stock-group
      kafka:
        binder:
          autoCreateTopics: true
          replicationFactor: 1
          brokers: ${app.kafka.brokers}


app:
  postgres:
    host: betting-postgres
    port: 5432
    database: orderdb
    user: orderdbuser
    password: dbpass

  kafka:
    brokers: "my-cluster-kafka-bootstrap:9092"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    net.skycomposer.betting: DEBUG
    org.springframework.cloud.kubernetes: TRACE
    org.springframework.security: DEBUG

openapi:
  oauthflow:
    authServerUrl: ${spring.keycloak.server-external-url}
    realm: betting-realm

jwt:
  auth:
    converter:
      resource-id: betting-app
      principal-attribute: preferred_username