#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $BETTING_DB_USER WITH PASSWORD '$BETTING_DB_PASSWORD';
    CREATE DATABASE $BETTING_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $BETTING_DB_NAME TO $BETTING_DB_USER;
    ALTER DATABASE $BETTING_DB_NAME SET TIMEZONE='Europe/Amsterdam';
    \c $BETTING_DB_NAME
    ALTER SCHEMA public OWNER TO $BETTING_DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $BETTING_DB_USER;
EOSQL