#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-label-xyz
  name: my-deployment-name 
spec:
  replicas: 3
  selector:
    matchLabels:
     app: to-find-nodes-and-form-the-cluster
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: to-find-nodes-and-form-the-cluster
        actorSystemName: betting-house 
    spec:
      serviceAccountName: my-cluster # check this name is right
      containers:
      - name: my-container-name
        image: $CONTAINER_REGISTRY/betting-house:$VERSION
        # Remove for a real project, the image is picked up locally for the integratio test
        imagePullPolicy: IfNotPresent
        #health
        livenessProbe:
          httpGet:
            path: /alive
            port: management
        readinessProbe:
          httpGet:
            path: /ready
            port: management
        #health
        ports:
        # akka-management bootstrap
        - name: management
          containerPort: 8558
          protocol: TCP
          # when contact-point-discovery.port-name is set for cluster bootstrap,
          # the management port must be named accordingly:
          # name: management
        - containerPort: 9000
        - containerPort: 9001
        - containerPort: 9002
        - containerPort: 9003
        env:
        # The Kubernetes API discovery will use this service name to look for
        # nodes with this value in the 'app' label.
        # This can be customized with the 'pod-label-selector' setting.
        - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app']"
        - name: JAVA_OPTS
          value: "-Xmx1024m -Ddockerized=true"

---
apiVersion: v1
kind: Service
metadata:
  name: betting-house
  labels:
    app: betting-house
spec:
  selector:
    app: to-find-nodes-and-form-the-cluster
  ports:
  - name: management
    port: 8558
    targetPort: 8558
  - name: betting
    port: 9000
    targetPort: 9000
  - name: betting-projection
    port: 9003
    targetPort: 9003  
  - name: market
    port: 9002
    targetPort: 9002      
  - name: wallet
    port: 9001
    targetPort: 9001