apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: $CONTAINER_REGISTRY/inventory-service:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9002
        - containerPort: 8002
        env:
        - name: SERVER_PORT
          value: "9002"
        - name: BPL_JVM_THREAD_COUNT
          value: "50"
        - name: BPL_DEBUG_ENABLED
          value: "true"
        - name: BPL_DEBUG_PORT
          value: "8002"
        - name: SPRING_KEYCLOAK_SERVER_URL
          value: "http://betting-keycloak:8080"
        - name: SPRING_KEYCLOAK_SERVER_EXTERNAL_URL
          value: "http://localhost:8080"
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]

---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  selector:
    app: inventory
  ports:
  - name: prod
    port: 9002
    targetPort: 9002
  - name: debug
    port: 8002
    targetPort: 8002