apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
      - name: keycloak-postgres
        image: postgres:15.3
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
        volumeMounts:
        - name: keycloak-postgres-dbcreation-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: keycloak-postgres-dbcreation-script
        configMap:
          name: keycloak-postgres-dbcreation-script

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
spec:
  selector:
    app: keycloak-postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP          