apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: $CONTAINER_REGISTRY/order-service:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9003
        - containerPort: 8003
        env:
        - name: SERVER_PORT
          value: "9003"
        - name: BPL_JVM_THREAD_COUNT
          value: "50"
        - name: BPL_DEBUG_ENABLED
          value: "true"
        - name: BPL_DEBUG_PORT
          value: "8003"
        - name: SPRING_KEYCLOAK_SERVER_URL
          value: "http://betting-keycloak:8080"
        - name: SPRING_KEYCLOAK_SERVER_EXTERNAL_URL
          value: "http://localhost:8080"
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]

---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
  - name: prod
    port: 9003
    targetPort: 9003
  - name: debug
    port: 8003
    targetPort: 8003