apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betting-connect
  template:
    metadata:
      labels:
        app: betting-connect
    spec:        
      containers:
      - name: betting-connect
        image: debezium/connect:2.2
        ports:
        - containerPort: 8083
        env:
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "connect_configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "connect_offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "connect_statuses"          
        - name: BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: betting-connect
spec:
  selector:
    app: betting-connect
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  type: LoadBalancer    