apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betting-postgres
  template:
    metadata:
      labels:
        app: betting-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: dbpass
          image: $CONTAINER_REGISTRY/betting-postgres:$VERSION
          name: betting-postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: betting-postgres
spec:
  selector:
    app: betting-postgres
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  type: LoadBalancer      